---
{% raw -%}
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    gcp_auth_kind: "{{ molecule_yml.driver.auth_kind }}"
    gcp_zone: "{{ molecule_yml.driver.zone }}"
    gcp_scopes: "{{ molecule_yml.driver.scopes }}"
    gcp_project: "{{  molecule_yml.driver.project_id }}"
    gcp_sa_mail: "{{ molecule_yml.driver.service_account_email }}"
    gcp_sa_file: "{{ molecule_yml.driver.service_account_file }}"

  tasks:
    - name: Destroy molecule instance(s)
      google.cloud.gcp_compute_instance:
        name: "{{ item.name }}"
        state: absent
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        scopes: "{{ gcp_scopes }}"
        service_account_email: "{{ gcp_sa_mail }}"
        service_account_file: "{{ gcp_sa_file }}"
        auth_kind: "{{ gcp_auth_kind) }}"
      register: async_results
      loop: "{{ molecule_yml.platforms }}"
      async: 7200
      poll: 0
      notify:
        - "Wipe out instance config"
        - "Dump instance config"

    - name: Wait for instance(s) deletion to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: server
      until: server.finished
      retries: 300
      delay: 10
      loop: "{{ async_results.results }}"

  handlers:
    - name: Import main handler tasks
      import_tasks: handlers/main.yml
{%- endraw %}