[build-system]
requires = [
  "setuptools >= 42.0.2",
  "setuptools_scm >= 1.15.0",
  "setuptools_scm_git_archive >= 1.0",
  "wheel",
  "google-api-python-client",
  "oauth2client",
  "pycryptodome"
]
build-backend = "setuptools.build_meta"
