---
dependency:
  name: galaxy
driver:
  name: gce
  project_id: change-to-id-of-the-gcp-project #  if not set, will default to env GCE_PROJECT_ID
  network_name: null #  specify if other than default
  subnetwork_name: null #  specify if other than default
  vpc_host_project: null #  if you use a shared vpc, set here the vpc host project. In such case, your gcp user needs the necessary permissions in the host project, see https://cloud.google.com/vpc/docs/shared-vpc#iam_in_shared_vpc
  auth_kind: null #  set to machineaccount or serviceaccount or application - if set to null will read env GCP_AUTH_KIND
  service_account_email: null #  set to an email associated with the project - if set to null, will default to GCP_SERVICE_ACCOUNT_EMAIL. Should not be set if using auth_kind serviceaccount.
  service_account_file: null #  set to the path to the JSON credentials file - if set to null, will default to env GCP_SERVICE_ACCOUNT_FILE
  scopes:
    - "https://www.googleapis.com/auth/compute" #  will default to env GCP_SCOPES, https://www.googleapis.com/auth/compute is the minimum required scope.
  region: null #  REQUIRED. example: us-central1
  external_access: false #  chose whether to create a public IP for the VM or not - default is private IP only
  instance_os_type: linux #  will be considered linux by default, but can be explicitely set to windows
platforms:
  - name: instance #  REQUIRED is an instance name
    machine_type: null #  If not specified, will default to n1-standard-1
    zone: null #  example: us-west1-b, will default to zone b of driver.region
    disk_size_gb: null #  Set only if needed
    image: 'projects/debian-cloud/global/images/family/debian-10' #  Points to an image, you can get a list of available images with command 'gcloud compute images list'.
      #  The expected format of this string is projects/<project>/global/images/family/<family-name>
      #  (see https://googlecloudplatform.github.io/compute-image-tools/daisy-automating-image-creation.html)
      #  Wille default to debian-10 image for os_type Linux, Windows 2019 for os_type Windows
    image_encryption_key: null #  only set it if you encrypt your images with your own encryption key
provisioner:
  name: ansible
verifier:
  name: ansible
